Việc tính toán softmax yêu cầu ba bước: 

(i) lũy thừa từng số hạng; 

(ii) cộng tổng các số hạng trên mỗi hàng để tính hằng số chuẩn hóa cho mỗi ví dụ; 

(iii) chia mỗi hàng cho hằng số chuẩn hóa của nó, đảm bảo tổng kết quả bằng 1:

**Lưu ý**: đây chỉ là hàm minh họa cách softmax hoạt động, không nên sử dụng trong thực tế vì nó chưa tối ưu như các framewwork hiện đại làm

In [25]:
import torch

def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(2, keepdims=True)
    return X_exp / partition  # The broadcasting mechanism is applied here

lưu ý cách sử dụng của torch.sum()

số 1 được truyền vào là chiều mà nó sẽ tính tổng, thay vì không truyền, nó sẽ tính tổng toàn bộ tensor X

ví dụ ta có X.shape = [1, 2, 3]

việc truyền 1 (tức axis = 1) là tính chiều tổng theo thứ 2 của tensor X

In [17]:
X = torch.tensor([[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]])
print(X.shape)

torch.Size([1, 2, 3])


In [19]:
X.sum(axis = 2, keepdims=True)

tensor([[[ 6.],
         [15.]]])

In [24]:
print(softmax(X).squeeze())

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


Phần tính mất mát entropy chéo

ví dụ phân loại 3 lớp: 0, 1, 2

In [ ]:
y = torch.tensor([0, 2]) # nhãn đúng thực tế
# Dự đoán xác suất cho mỗi lớp của 2 mẫu 0, 1
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y] #xác suất dự đoán đúng
# [0, 1] ở đây là chỉ số của mỗi sample

tensor([0.1000, 0.5000])

In [28]:
#tính loss hàm mất mát cross-entropy bằng cách 
#lấy log và lấy trung bình

def cross_entropy(y_hat, y):
    return -torch.log(y_hat[list(range(len(y_hat))), y]).mean()

cross_entropy(y_hat, y)

tensor(1.4979)