In [ ]:
!nvidia-smi

Sat Jan 17 03:39:12 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.__version__

'2.9.0+cpu'

In [6]:
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

CUDA available: True
GPU: Tesla T4


In [9]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [12]:
import numpy as np
np_array = np.array(data)
x_np = torch.tensor(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [15]:
# Tensor mới giữ nguyên các thuộc tính (hình dạng, kiểu dữ liệu)
# của tensor đối số, trừ khi được ghi đè một cách rõ ràng
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9267, 0.9613],
        [0.5960, 0.0954]]) 



In [ ]:
#Khởi tạo tensor với shape định nghĩa trước

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1490, 0.6583, 0.2894],
        [0.4096, 0.0745, 0.0966]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 3 kiểu dữ liệu quan trọng nhất, thường là nguyên nhân gây ra các lỗi của pytorch

tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [19]:
# chuyển tensor vào gpu

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [20]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0 # duyệt tất cả các hàng, đặt giá trị các ptu cột thứ 2 bằng = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [23]:
#ghép tensor

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [ ]:
# các phép toán cơ bản + - đơn giản, ngoài ra nếu 1 tensor cộng với 1 số, pytorch sẽ tự map số đó
# thành tensor có kích thước = tensor ban đầu

In [24]:
#Nhân các tensor
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# nhân ma  chỉ hoạt động khi hai tensor đúng kích thước (số cột = số hàng)

# (3, 2) @ (3, 2)sẽ không hoạt động
# (2, 3) @ (3, 2)sẽ hoạt động
# (3, 2) @ (2, 3)sẽ hoạt động


print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
# Các thao tác có hậu tố '_' được gọi là thao tác tại chỗ. Ví dụ: x.copy_(y), x.t_(), sẽ thay đổi x.

print(tensor, "\n")
tensor.add_(5)
print(tensor)

# Các thao tác tại chỗ giúp tiết kiệm bộ nhớ, nhưng có thể gây ra vấn đề khi tính toán
# đạo hàm do mất dữ liệu lịch sử ngay lập tức. Do đó, việc sử dụng chúng không được khuyến khích.

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Mô-đun này torch.nn.Linear()(chúng ta sẽ thấy nó hoạt động sau), còn được gọi là lớp truyền thẳng hoặc lớp kết nối đầy đủ, thực hiện phép nhân ma trận giữa ma trận đầu vào x và ma trận trọng số A.
$$ y = x\cdot{A^T} + b $$

In [5]:

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
# Vì lớp tuyến tính bắt đầu với ma trận trọng số ngẫu nhiên, hãy làm cho nó có thể tái tạo được (sẽ nói thêm về điều này sau) 
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [6]:
# reshape

x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape
# có thể dùng view() để reshape mà không cần truyền tham số nhưng khi thay đổi data trên view cũng sẽ thay đổi x

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [8]:
# có thể dùng squeeze() để xóa chiều có dim = 1
x_squeeze =x_reshaped.squeeze()
x_squeeze, x_squeeze.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Đôi khi bạn sẽ muốn chọn dữ liệu cụ thể từ các tensor (ví dụ: chỉ cột đầu tiên hoặc hàng thứ hai).

Để làm được điều đó, bạn có thể sử dụng phương pháp lập chỉ mục.

Nếu bạn đã từng thực hiện việc lập chỉ mục trên danh sách Python hoặc mảng NumPy, thì việc lập chỉ mục trong PyTorch với tensor cũng rất tương tự.

In [9]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [10]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Bạn cũng có thể sử dụng : để chỉ định "tất cả các giá trị trong chiều này" và sau đó sử dụng dấu phẩy (,) để thêm một chiều khác.

In [11]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [12]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [13]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

Vì NumPy là một thư viện tính toán số học phổ biến trong Python, PyTorch có chức năng tương tác tốt với nó.

Hai phương pháp chính bạn nên sử dụng để chuyển đổi từ NumPy sang PyTorch (và ngược lại) là:

torch.from_numpy(ndarray)- Chuyển đổi mảng NumPy thành tensor PyTorch.

torch.Tensor.numpy()- Chuyển đổi tensor PyTorch sang mảng NumPy.

In [15]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Lưu ý: Theo mặc định, mảng NumPy được tạo với kiểu dữ liệu float64và nếu bạn chuyển đổi nó thành tensor PyTorch, nó sẽ giữ nguyên kiểu dữ liệu (như trên).

Tuy nhiên, nhiều phép tính trong PyTorch mặc định sử dụng float32.

Vì vậy, nếu bạn muốn chuyển đổi mảng NumPy (float64) -> tensor PyTorch (float64) -> tensor PyTorch (float32), bạn có thể sử dụng
 
 tensor = torch.from_numpy(array).type(torch.float32)

Thay đổi tensor mảng vẫn giữ nguyên

In [16]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Về khả năng tái tạo lại kết quả bằng cách cố định cách ngẫu nhiên

In [17]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]])

Tensor B:
tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])