# 00. Bài tập Cơ bản về PyTorch

### 1. Đọc tài liệu

Một phần quan trọng của học sâu (và học lập trình nói chung) là làm quen với tài liệu của một framework cụ thể mà bạn đang sử dụng. Chúng ta sẽ sử dụng tài liệu PyTorch rất nhiều trong suốt phần còn lại của khóa học này. Vì vậy, tôi khuyên bạn nên dành 10 phút để đọc những tài liệu sau (không sao nếu bạn chưa hiểu một số điều ngay bây giờ, trọng tâm chưa phải là hiểu hoàn toàn, mà là nhận thức).
  * Tài liệu về [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * Tài liệu về [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Tạo một tensor ngẫu nhiên có kích thước `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(size=(7, 7))
tensor

tensor([[0.9307, 0.8333, 0.6175, 0.6639, 0.2090, 0.8561, 0.8303],
        [0.9479, 0.9522, 0.7771, 0.7209, 0.5619, 0.9112, 0.3688],
        [0.0090, 0.2787, 0.0668, 0.3162, 0.2369, 0.4551, 0.8955],
        [0.0172, 0.7518, 0.4238, 0.0796, 0.8734, 0.9125, 0.2994],
        [0.5336, 0.3944, 0.5871, 0.8813, 0.0643, 0.9283, 0.2657],
        [0.1641, 0.4511, 0.7424, 0.5157, 0.6061, 0.5993, 0.7087],
        [0.7490, 0.3118, 0.8553, 0.6640, 0.4019, 0.5260, 0.1659]])

### 3. Thực hiện phép nhân ma trận trên tensor ở bước 2 với một tensor ngẫu nhiên khác có kích thước `(1, 7)` (gợi ý: bạn có thể phải chuyển vị tensor thứ hai).

In [2]:
# Create another random tensor
tensor_2 = torch.rand(size=(1, 7))
# Perform matrix multiplication 
ans = tensor @ tensor_2.T
ans

tensor([[2.3076],
        [2.2613],
        [1.0851],
        [1.1916],
        [1.6506],
        [1.6988],
        [1.6584]])

### 4. Đặt random seed thành `0` và thực hiện lại bước 2 & 3.

Kết quả đầu ra nên là:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(size=(7, 7))
t2 = torch.rand(size=(1, 7))


# Matrix multiply tensors
anw = t1 @ t2.T
anw, anw.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Nói về random seed, chúng ta đã thấy cách đặt nó với `torch.manual_seed()`, vậy có tương đương trên GPU không? (gợi ý: bạn cần xem tài liệu về `torch.cuda` cho phần này)
  * Nếu có, hãy đặt random seed trên GPU thành `1234`.

In [5]:
# Set random seed on the GPU



### 6. Tạo hai tensor ngẫu nhiên có kích thước `(2, 3)` và chuyển cả hai lên GPU (bạn cần có GPU cho phần này). Đặt `torch.manual_seed(1234)` khi tạo các tensor (không nhất thiết phải là random seed trên GPU). Kết quả đầu ra sẽ giống như sau:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Thực hiện phép nhân ma trận trên các tensor bạn đã tạo ở bước 6 (bạn có thể phải điều chỉnh kích thước của một trong các tensor).

Kết quả đầu ra sẽ giống như:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Tìm giá trị lớn nhất và nhỏ nhất của kết quả ở bước 7.

In [8]:
# Find max

# Find min


### 9. Tìm chỉ số lớn nhất và nhỏ nhất của kết quả ở bước 7.

In [9]:
# Find arg max


# Find arg min



### 10. Tạo một tensor ngẫu nhiên có kích thước `(1, 1, 1, 10)` rồi tạo một tensor mới bằng cách loại bỏ tất cả các chiều có giá trị `1` để còn lại tensor có kích thước `(10)`. Đặt seed là `7` khi tạo và in ra cả hai tensor cùng với kích thước của chúng.

Kết quả đầu ra sẽ giống như:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [8]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t3 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
t4 = t3.squeeze()

# Print out tensors and their shapes
t3, t3.shape, t4, t4.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))