- Framework khởi tạo param ngẫu nhiên cho mỗi lớp
- Dưới đây là một số cách khởi tạo khác nhau

In [1]:
import torch
from torch import nn

Theo mặc định, PyTorch khởi tạo ma trận trọng số và ma trận độ lệch một cách đồng nhất bằng cách lấy mẫu từ một phạm vi được tính toán dựa trên kích thước đầu vào và đầu ra
- nn.init cung cấp nhiều phương pháp khởi tạo được thiết lập sẵn

In [ ]:
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.rand(size=(2, 4))
net(X).shape

torch.Size([2, 1])

Chúng ta hãy bắt đầu bằng cách gọi các hàm khởi tạo tích hợp sẵn. Đoạn mã dưới đây khởi tạo tất cả các tham số trọng số dưới dạng các biến ngẫu nhiên Gaussian với độ lệch chuẩn 0,01, trong khi các tham số độ lệch được đặt về 0.

In [3]:
def init_normal(module):
    if type(module) == nn.Linear:
        nn.init.normal_(module.weight, mean=0, std=0.01)
        nn.init.zeros_(module.bias)

net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([-0.0111, -0.0051,  0.0008, -0.0017]), tensor(0.))

In [4]:
# khởi tạo tất cả các param với hằng số 
def init_constant(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 1)
        nn.init.zeros_(module.bias)

net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [5]:
# khởi tạo cho từng layer
def init_xavier(module):
    if type(module) == nn.Linear:
        nn.init.xavier_uniform_(module.weight)

def init_42(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 42)

net[0].apply(init_xavier)
net[2].apply(init_42)
print(net[0].weight.data[0])
print(net[2].weight.data)

tensor([ 0.5633, -0.2947, -0.6236, -0.4977])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])
